### ISSUE TITLE
Outlines outside of the month/day structure crash OldSchool

### ISSUE THREAD

**Issue by andrewshell** [scripting/oldSchoolBlog#2]
[My Outline JSON](http://storage.shll.me:1229/users/andrewshell/electric/osgeekity.json)

**config.json**

```json
{
    "blogs": {
                "andrew": {
                        "title": "os.geekity.com",
                        "link": "http://os.geekity.com/",
                        "description": "Andrew's kicking it old school.",
                        "urlJson": "http://storage.shll.me:1229/users/andrewshell/electric/osgeekity.json",
                        "basePath": "/os.geekity.com/",
                        "basePathItems": "/os.geekity.com/data/items/",
                        "baseUrl": "http://os.geekity.com/",
                        "language": "en-us",
                        "generator": "oldSchool v0.46f",
                        "docs": "http://cyber.law.harvard.edu/rss/rss.html",
                        "docsForJsonFeed": "https://github.com/scripting/Scripting-News/blob/master/rss-in-json/README.md",
                        "twitterScreenName": "andrewshell",
                        "facebookPageName": "Andrew Shell",
                        "maxFeedItems": 50,
                        "appDomain": "os.geekity.com",
                        "flRssCloudEnabled": true,
                        "rssCloudDomain": "rpc.rsscloud.io",
                        "rssCloudPort": 5337,
                        "rssCloudPath": "/pleaseNotify",
                        "rssPingPath": "/ping",
                        "rssCloudRegisterProcedure": "",
                        "rssCloudProtocol": "http-post",
                        "customPages": [],
                        "maxDaysOnHomePage": 25,
                        "flUploadItemsToS3": true,
                        "urlHeaderImage": "http://os.geekity.com/2020/10/hello-i-m-nik-WynwKOGstCw-unsplash.jpg",
                        "urlHomePageTemplate": "http://os.shll.me/template.html",
                        "urlTemplate": "http://os.shll.me/template.html",
                        "flIncludeImageInMetadata": false,
                        "urlGlossaryOpml": "http://electricserver.scripting.com/users/davewiner/electric/glossary.opml",
                        "flGoogleAnalytics": false,
                        "idGoogleAccount": ""
                        }
            }
    }
```

**What I did:**

At the end of my outline I created a new outline (not using +) with
text: Test Page
attributes: name=testpage, type=outline

It has one sub with text "I don't think this will do anything, but what the hell"

I ran [http://os.shll.me:1400/build?blog=andrew](http://os.shll.me:1400/build?blog=andrew)

**What I expected:**

I thought it would either create a new top level page /testpage.html or ignore the new outline entirely.

**What happened:**

It failed in chrome with an error empty response (no status code)

There was an error in the console

```
2|oldschool  | TypeError: Cannot read property 'length' of undefined
2|oldschool  |     at publishDay (/home/shellab/oldSchoolBlog/oldschool.js:705:32)
2|oldschool  |     at publishNextDay (/home/shellab/oldSchoolBlog/oldschool.js:737:4)
2|oldschool  |     at /home/shellab/oldSchoolBlog/oldschool.js:738:5
2|oldschool  |     at /home/shellab/oldSchoolBlog/oldschool.js:731:5
2|oldschool  |     at /home/shellab/oldSchoolBlog/oldschool.js:510:6
2|oldschool  |     at /home/shellab/oldSchoolBlog/oldschool.js:275:5
2|oldschool  |     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
```

**Expectations**

Just don't crash. It can ignore the node.

We can discuss feature requests later, not important right now.

**Comment by andrewshell** [comment]
```
2|oldschool  | TypeError: Cannot read property 'length' of undefined
2|oldschool  |     at publishRssFeed (/home/shellab/oldSchoolBlog/oldschool.js:995:33)
2|oldschool  |     at /home/shellab/oldSchoolBlog/oldschool.js:1157:7
2|oldschool  |     at publishNextDay (/home/shellab/oldSchoolBlog/oldschool.js:763:5)
2|oldschool  |     at /home/shellab/oldSchoolBlog/oldschool.js:758:5
2|oldschool  |     at /home/shellab/oldSchoolBlog/oldschool.js:750:6
2|oldschool  |     at /home/shellab/oldSchoolBlog/oldschool.js:518:6
2|oldschool  |     at /home/shellab/oldSchoolBlog/oldschool.js:281:5
2|oldschool  |     at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
```

http://storage.shll.me:1229/users/andrewshell/electric/osgeekity.opml

**Comment by andrewshell** [comment]
Good news! v0.6.6 no longer crashes with a non calendar entry.
